name: Scheduled lint 

on:
    schedule:
    # 


# This is based on UBCSailbot/docs/weekly-lint.yml
jobs:
  # https://github.com/gaurav-nelson/github-action-markdown-link-check
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Check markdown pages for broken links
      uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        config-file: '.markdown-link-check.json'
        folder-path: 'docs'
        file-path: './README.md'