name: Scheduled tasks

on:
    # Run scheduled tasks every x 
    schedule:
    # Use cron generator to generate a cron schedule
        #e.g: At 4:05 AM every 15th day of each month
        - cron: 5 4 15 * *


# This is based on UBCSailbot/docs/weekly-lint.yml
# Jobs are the tasks ran every schedule you have defined above - cron: ...
jobs:
  # https://github.com/gaurav-nelson/github-action-markdown-link-check
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Check markdown pages for broken links
      uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        config-file: '.markdown-link-check.json'
        folder-path: 'docs'
        file-path: './README.md'